actions:
  eslint:
    run: yarn eslint --max-warnings 0 {files}
    fix: yarn eslint --max-warnings 0 --fix {files}
    include:
      - "*.js"
      - "*.jsx"
  stylelint:
    run: yarn stylelint {files}
    include:
      - "*.css"
      - "*.less"
  nsp:
    run: yarn nsp check
