actions:
  eslint:
    run: ./node_modules/.bin/eslint --max-warnings 0 {files}
    include:
      - "*.js"
      - "*.jsx"
  stylelint:
    run: ./node_modules/.bin/stylelint {files}
    include:
      - "*.css"
      - "*.less"
