status = [
  "ci/circleci: build",
  "ci/circleci: docs",
  "ci/circleci: test",
  "ci/circleci: lint",
]
block_labels = ["bors-dont-merge"]
required_approvals = 1
delete_merged_branches = true
# Avoid including verbose details in commit messages
cut_body_after = "\n---\n"
