# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:

    docker:
      # Based on https://nodejs.org/en/
      - image: circleci/node:8-browsers@sha256:22e4d1c8a61a410b64cf73057cd0f8f391ca563211c40829f0a465dc53155749

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run linting check!
      - run: yarn run lint

      # run tests!
      - run: yarn run test

      # build all the things!
      - run: yarn run build

  docs:
    docker:
      - image: circleci/python:3.6@sha256:2e1902ea05943d983ce35bf0155835ad754417521dac51358cf08ed23cc9b98f

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "docs/requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r docs/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "docs/requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd docs
            make html


workflows:
  version: 2
  build_and_docs:
    jobs:
      - build
      - docs
