# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:

    docker:
      # Based on https://nodejs.org/en/
      - image: circleci/node:8-browsers@sha256:298e7fe2e286a4677a7ded027f09a3e2ff76d7eb0c6ffa958c145fc23ec4ae09

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run linting check!
      - run: yarn run lint

      # run tests!
      - run: yarn run test

      # build all the things!
      - run: yarn run build

  docs:
    docker:
      - image: circleci/python:3.6@sha256:128fcd2ffa0d5bc9c3b17c4ac306cdd246b969b34f229f04111d8ab40b1abf0f

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "docs/requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r docs/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "docs/requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd docs
            make html


workflows:
  version: 2
  build_and_docs:
    jobs:
      - build
      - docs
